# Generated by Django 5.2.9 on 2026-01-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crn", models.IntegerField()),
                ("output_file", models.FileField(upload_to="")),
                ("upload_date", models.DateField()),
                ("upload_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UploadedFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crn", models.IntegerField()),
                ("input_file", models.FileField(upload_to="")),
                ("upload_date", models.DateField()),
                ("upload_time", models.TimeField()),
                ("processed", models.BooleanField()),
            ],
        ),
    ]
