# Generated by Django 5.2.9 on 2026-01-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bit_calculator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedfiles",
            name="upload_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="generatedfiles",
            name="upload_time",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="uploadedfiles",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="uploadedfiles",
            name="upload_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="uploadedfiles",
            name="upload_time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
