# Generated by Django 5.2.9 on 2026-01-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bit_calculator", "0002_alter_generatedfiles_upload_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crn", models.IntegerField()),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("upload_time", models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
