# Generated by Django 5.2.9 on 2025-12-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csvFiles", models.FileField(upload_to="")),
                ("upload_date", models.DateTimeField()),
                ("crn", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Rewards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bit_rewards", models.CharField()),
                ("week", models.IntegerField()),
                ("crn", models.IntegerField()),
                ("last_updated", models.DateTimeField()),
            ],
        ),
    ]
