# Generated by Django 5.2.9 on 2025-12-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bit_calculator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labsections",
            old_name="csvFiles",
            new_name="csv_input_file",
        ),
    ]
